### ISSUE TITLE
Jobeserver fails with 3 Python3 tests under debian stretch

### ISSUE THREAD

**Issue by kiliansinger** [trampgeek/jobe#10]
Under debian stretch:
"Python3 file io" test fails and two other file io related python3 tests.
Reported error: PermissionError: [Errno 13] Permission denied: 'testoutput.txt'
When compared to ubuntu 16.04LTS jobeserver creates folder in /home/jobe/runs/ with access
 right 755 (debian) instead of 765 (ubuntu). 
Other possible cause:
when calling as www-data this works in both debian and ubuntu:
su - www-data -s /bin/bash -c 'cd /home/jobe/runs/jobe_PYTHONIO_ID && python3 /home/jobe/runs/jobe_PYTHONIO_ID/test.py
but this only works in ubuntu:
su - jobe00 -s /bin/bash -c 'cd /home/jobe/runs/jobe_PYTHONIO_ID && python3 /home/jobe/runs/jobe_PYTHONIO_ID/test.py

Reason for using debian stretch is use of grsecurity, which is offically supported in backports and soon hopefully in stable releases. Also debian jessie fails with many errors that language 'c' and 'java' are unknown.
I guess it is a version problem, which I do not see any reason to fix.

PS: debugging and verbose mode was enabled.

**Comment by trampgeek** [comment]
Hi

Thanks for reporting this.

I don't think the problem is with the access rights of the folder. I 
tried inserting chmod($this->workdir, 0755) into my own Jobe to mimic 
your Debian system and it had no effect. Write access by the subprocess 
to its work directory should be being set by line 242 in LanguageTask.php

exec("setfacl -m u:$user:rwX $workdir");

It seems to me that the most likely explanation is that GRSecurity is 
either preventing that line from functioning or is overriding it with 
its own RBAC layer (Rule Based Access Control). I just tried commenting 
the setfacl line out on my server and, I think, replicated your result. 
Specifically, the following three tests all failed with Permission 
denied errors: Python3 file I/O, Valid Python3/pylint program, Invalid 
Python3/pylint program. Are those exactly the same tests as failed for you?

I don't think I can easily fix this within Jobe. It seems to call for a 
special GRsecurity rule to enable the required file access. I see at 
https://en.wikibooks.org/wiki/Grsecurity/The_RBAC_System that you can 
customise the security policies, but understanding exactly how to do 
that would take me rather a long time and I don't currently even have a 
GRSecurity system to test with.

If you do find a way of solving the problem with security policies, I'd 
be most grateful if you'd post it here (or email it to me) and I'll 
include it in the documentation.

I have had similar problems in the past, trying to run a predecessor of 
Jobe with SELinux enabled. After banging my head against a wall for some 
time I came to the conclusion that a system like Jobe, which is 
specifically designed to run untrusted student code, is bound to 
conflict to some extent with security-enhanced systems designed to 
prevent such things happening! So I just turned off SELinux :)

Richard

**Comment by kiliansinger** [comment]
Hi Richard,
my goal is to use grsecurity in future. For the reported issue it was not
even installed.

The tests which fail are indeed:
Python3 file I/O, Valid Python3/pylint program and invalint Python3/pylint program.

Oh and I realized that the folders in ubuntu have a drwxrwxr-x+ but in debian they have not.
Also getfacl does not work there. So I must miss some prerequisites which are not automatically installed under debian. And indeed after: "sudo apt install acl" all test runs complete without errors. 

Thanks a lot for the hint with setfacl.

We have set up a kvm server with all needed settings to run moodle with
stack and coderunner. Additionally for exams the safe exam browser can be booted from a pxe server. Also intallation scripts are available (being tricky as only debian stretch from before december works, but the install scripts for the creation of the images work on any version by temporarily downgrading the system). Currently all installation scripts exist and are working. I can also send them to you.

Hardening is now the next step. As the jobe server has a large attack surface we are currently trying to harden the jobe server. All the changeroot things are easily broken by kernel exploits and grsecurity can be very efficient for those issues. You can nearly totally suppress stack overflow issues.
 
For all settings I can supply the scripts necessary. Currently this includes moodle, maximapool, stack and jobe server setup. The kvm scripts are currently under development. I would love to share them all to the community. I already uploaded the maximapool installation script to the github. I will keep you updated with the hardening settings.

Best regards and thanks for the fast reply.
Kilian

PS: I will send a pullrequest to update the doc.

**Comment by trampgeek** [comment]
Hi Kilian
Good to know the problem is resolved. Thanks for the pull request - I've merged it in. Good luck with the hardening - I look forward to hearing what you come up with.

Richard
