### ISSUE TITLE
Suggestion: have c and cpp templates remove $this->src before execution

### ISSUE THREAD

**Issue by dirkcgrunwald** [trampgeek/jobe#2]
Some very clever students determined the test cases to their quiz questions by using popen to then cat prog.cpp and get a copy of the template source. I added unlink($this->src) to fix this for C/C++, but for many languages there is no work around (e.g. python2/3) that I can think of.

**Comment by trampgeek** [comment]
Interesting. The way we use Jobe (from CodeRunner) the test cases are mostly exposed anyway, apart from the odd hidden test intended only to defeat people who synthesise a program that simply generates the expected output from the given input. So it's not a serious problem for us, but it most definitely *is* a deficiency.

I like your solution for compiled languages, though you'd want the deletion of the source to be conditional on debugging being off. [The debug option leaves all files undeleted so you can see everything that happened during the run.] Interpreted languages are more problematic. One approach might be to change the template so that it deletes the source code before the student's code gets executed, e.g. in python3:

    import os
    os.unlink('prog.python3')
    {{STUDENT_ANSWER}}
    {{TEST.testcode}}

This works, at least with the Jobe sandbox, but it is sandbox specific.

Thanks for pointing out the problem. I'd like to mull it over a bit more before taking any action.

-- Richard

**Comment by trampgeek** [comment]
For the benefit of anyone who's puzzled by my reference to changing the template, above, I should have pointed out that that was a fix only if you're using Jobe from CodeRunner. It's irrelevant if you're running Jobe from some other application.

**Comment by trampgeek** [comment]
After much navel gazing, I've decided this isn't actually a Jobe issue at all. Jobe provides an upload-and-execute service that gives you back the program's output. The execution environment is unrestricted, subject only to resource constraints and other security restrictions imposed by the Linux host. Files can be loaded into the current directory so the program must be able to read them. Writing of files into that environment is also supported - some CodeRunner questions require this. Other system calls such as forks are allowed too, again subject to resource limits. In an open context like this, it is inevitable that programs will be able to inspect their execution environment and/or perform introspection operations. So I no longer think the problem you have identified is a defect in Jobe.

It might however be argued that you've put your finger on a defect in CodeRunner. You could post your concerns on the CodeRunner repository, if you like Dirk, and I can then respond there. FYI, I'll argue that the information leak isn't really a concern unless you're using combinator templates. If you disable the combinator, each test is run independently and you have the option of showing or hiding each test case separately. The CodeRunner philosophy is generally to reveal each test. Hidden test cases are used only to prevent students synthesising a program of the form `if testA print expectedA elseif testB print expectedB ...`.  

-- Richard
