### ISSUE TITLE
testsubmit.py fails 1 test "15, 'cmpinfo'"

### ISSUE THREAD

**Issue by dave559** [trampgeek/jobe#26]
I have just cloned/installed the current version of jobe (as at about 1 hour ago) from the git repo onto an Ubuntu 18.04 server.

(I have set the Apache envvars value of `LANG` to: `C.UTF-8`, if that is relevant.)

When running python3 testsubmit.py, all tests appear to be successful apart from one.
Is this anything to be concerned about?

Thanks, David.

$ python3 testsubmit.py 

Supported languages:
    c: 7.3.0
    cpp: 7.3.0
    java: 10.0.1
    nodejs: 8.10.0
    octave: 4.2.2
    pascal: 3.0.4
    php: 7.2.7
    python3: 3.6.5

Valid Python3 OK
Python3 with stdin OK
Syntactically invalid Python3 OK
Python3 runtime error OK
Python3 file I/O OK
Testing use of interpreter args with Python3 OK
Testing use of runargs args with Python3 OK
Python3 program with customised timeout OK
Python3 program with support files OK

***************** FAILED TEST ******************

{'run_id': None, 'outcome': 15, 'cmpinfo': '', 'stdout': '------------------------------------\n', 'stderr': ''}
Valid Python3/pylint program
Jobe result: Successful run

Output:
------------------------------------

************************************************

Invalid Python3/pylint program OK
UTF-8 output from Python3 (will fail unless Jobe set up for UTF-8) OK

[...tests continue OK...]

**Comment by trampgeek** [comment]
Certainly not a biggie. What seems to be happening here is that pylint3 (the program that's used to style-check python code) is generating spurious output on a stylistically valid Python program. I think the pylint3 config file may be wrong, resulting in the so-called "score" being output.

Would you mind repeating the following pylint3 config command given in the readme, please, making sure to execute it from a root-user prompt (e.g. via sudo bash) rather than simply prefixing the commands with sudo.

    pylint3 --reports=no --score=n --generate-rcfile > /etc/pylintrc

Then rerun the _testsubmit_ program and tell me what happens.

Richard

**Comment by dave559** [comment]
Thanks, Richard. Yes, that has solved the problem, all tests now report OK with no errors.

(My apologies: I had forgotten to update the pylint3 command with the new score parameter, mea culpa.)

**Comment by trampgeek** [comment]
Good to know the problem is solved. Enjoy.
