### ISSUE TITLE
Octave will not run

### ISSUE THREAD

**Issue by bnmnetp** [trampgeek/jobe#38]
Hi,

I'm getting the following error when trying to run an Octave problem with the RESTAPI

```
/usr/bin/octave-cli: error while loading shared libraries: libopenblas.so.0: failed to map segment from shared object
```

If I shell in to the server I can run octave-cli with no problems.  I've even tried ``runguard octave-cli`` and that also works.

Any ideas on where I should go from here?

**Comment by trampgeek** [comment]
Octave isn't one of the standard built-in languages in Jobe, so I'm not sure how you're running it through the RESTAPI. Via Python, perhaps? Regardless, the problem is almost certainly due to hitting one of the resource limits in the Runguard sandbox on Jobe. There are several discussions on such things in the CodeRunner forum, e.g. [this one](https://coderunner.org.nz/mod/forum/discuss.php?d=177). The various parameters are documented [here](https://github.com/trampgeek/jobe#run_spec-parameters). memorylimit, numprocs and disklimit are the usual culprits, in that order. Try a memorylimit of 0 for a start, which disables the check altogether. The environment variable OPENBLAS_NUM_THREADS might also be relevant - see [this thread](https://coderunner.org.nz/mod/forum/discuss.php?d=141).

**Comment by bnmnetp** [comment]
Thanks, I just figured it out myself by looking at the testsubmit.py script and noticing that you were setting the memorylimit for octave.  That has solved it.  Thanks for the quick answer!
