### ISSUE TITLE
How to pass SYSTEM.IN Param

### ISSUE THREAD

**Issue by tavivek** [trampgeek/jobe#45]
How can I send the SYSTEM.IN param over the body object.

Thanks

**Comment by trampgeek** [comment]
Sorry, I don't understand the question. Are you using Jobe from CodeRunner? If so, could you please post your question to the question author's forum on coderunner.org.nz, explaining what sort of question you're trying to set for the students. Alternatively, if you're using jobe stand-alone, could you explain your question in more detail please, but posting it as a  _Discussions_  item. I'm going to close this thread, since it's not actually an _Issue_ with Jobe.
